<template>
  <article :id="`care-scene-${scene.id}`" class="care-scene" :class="`care-scene--${scene.layout}`" :data-scene="scene.id" :aria-labelledby="`care-scene-title-${scene.id}`">
    <div class="care-scene__media">
      <img class="care-scene__image" :src="scene.image" :alt="scene.alt" :style="{ objectPosition: scene.objectPosition }" :loading="scene.id === '01' ? 'eager' : 'lazy'" decoding="async">
    </div>
    <div class="care-scene__copy">
      <div class="care-scene__meta"><span class="care-scene__number">{{ scene.id }}</span><span v-if="scene.id === '02'" class="care-scene__chapter">開始陪伴</span><time class="care-scene__time">{{ scene.time }}</time></div>
      <h2 :id="`care-scene-title-${scene.id}`" class="care-scene__title">{{ scene.title }}</h2>
      <p class="care-scene__description">{{ scene.description }}</p>
      <div v-if="scene.id === '02'" class="care-scene__hints" aria-label="常見照護需求">
        <span><CookingPot :size="20" />備餐</span><span><MessagesSquare :size="20" />陪伴</span><span><Shirt :size="20" />家務</span><span><Footprints :size="20" />外出</span>
      </div>
      <p v-if="scene.id === '08'" class="care-scene__closing">明天，又是新的日常。</p>
    </div>
  </article>
</template>

<script setup lang="ts">
import { CookingPot, Footprints, MessagesSquare, Shirt } from '@lucide/vue';
type SceneLayout = 'hero' | 'split' | 'cinematic' | 'reverse' | 'detail' | 'work' | 'outdoor' | 'ending';
interface CareScene { id: string; time: string; title: string; description: string; image: string; alt: string; layout: SceneLayout; objectPosition?: string }
defineProps<{ scene: CareScene }>();
</script>

<style scoped>
.care-scene__chapter{color:#6e5750;font-size:.78rem;font-weight:700;letter-spacing:.12em}
.care-scene{position:relative;width:min(1440px,100%);min-height:clamp(620px,76dvh,860px);display:grid;align-items:center;margin:auto;padding:clamp(80px,9vw,130px) max(24px,calc((100vw - 1440px)/2));color:#493833}
.care-scene__media{overflow:hidden;min-width:0;box-shadow:0 24px 70px #49383317}.care-scene__image{width:100%;height:100%;display:block;object-fit:cover;will-change:transform}.care-scene__copy{position:relative;z-index:1;max-width:500px}.care-scene__meta{display:flex;align-items:baseline;gap:14px;color:#c85618;font-variant-numeric:tabular-nums}.care-scene__number{font-size:clamp(2.2rem,4vw,4rem);font-weight:300;line-height:1}.care-scene__time{font-size:.95rem;font-weight:800;letter-spacing:.12em}.care-scene__title{margin:22px 0 14px;font-size:clamp(2.25rem,4.2vw,4.5rem);line-height:1.13;letter-spacing:-.04em}.care-scene__description{max-width:29em;margin:0;color:#6e5750;font-size:clamp(1rem,1.2vw,1.2rem);line-height:1.8}.care-scene__hints{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-top:34px}.care-scene__hints span{min-height:76px;display:grid;place-items:center;gap:5px;padding:10px;color:#6e5750;background:#fffdfbcc;border:1px solid #c8561826;border-radius:16px}.care-scene__hints svg{color:#c85618}.care-scene__closing{margin:clamp(50px,8vh,90px) 0 0;color:#6e5750;font-size:.88rem;letter-spacing:.12em}
.care-scene--hero{grid-template-columns:minmax(280px,38%) minmax(0,62%);gap:clamp(30px,5vw,72px)}.care-scene--hero .care-scene__media{order:2;height:clamp(480px,62vw,720px);border-radius:32px 0 0 32px}.care-scene--hero .care-scene__copy{order:1}.care-scene--hero .care-scene__number{position:absolute;right:0;bottom:-70px}
.care-scene--split{grid-template-columns:36% 64%;gap:clamp(28px,5vw,70px)}.care-scene--split .care-scene__media{order:2;height:min(48vw,680px);border-radius:30px}.care-scene--split .care-scene__copy{order:1}.care-scene--cinematic{grid-template-columns:68% 32%;gap:clamp(28px,5vw,70px);padding-left:0}.care-scene--cinematic .care-scene__media{height:min(50vw,740px);border-radius:0 32px 32px 0}.care-scene--reverse{grid-template-columns:34% 66%;gap:clamp(28px,5vw,70px);padding-right:0}.care-scene--reverse .care-scene__media{order:2;height:min(50vw,720px);border-radius:32px 0 0 32px}.care-scene--reverse .care-scene__copy{order:1}.care-scene--detail{grid-template-columns:58% 42%;gap:clamp(40px,7vw,110px)}.care-scene--detail .care-scene__media{aspect-ratio:4/3;border-radius:32px}.care-scene--detail .care-scene__image{transform-origin:38% center}.care-scene--work{grid-template-columns:38% 62%;gap:clamp(28px,5vw,70px)}.care-scene--work .care-scene__media{order:2;height:min(48vw,680px);border-radius:32px}.care-scene--work .care-scene__copy{order:1}.care-scene--outdoor{max-width:none;grid-template-columns:68% 32%;gap:clamp(28px,5vw,70px);padding-left:0;background:linear-gradient(100deg,#f3f0df,#e9f1e3,#edf4ef)}.care-scene--outdoor .care-scene__media{height:min(52vw,740px);border-radius:0 32px 32px 0}.care-scene--ending{max-width:none;height:clamp(620px,78dvh,880px);display:flex;align-items:center;padding:0;overflow:hidden}.care-scene--ending .care-scene__media{position:absolute;inset:0;box-shadow:none}.care-scene--ending .care-scene__media::after{position:absolute;inset:0;background:linear-gradient(90deg,#493833d9 0%,#49383394 34%,transparent 68%),linear-gradient(0deg,#49383370,transparent 45%);content:''}.care-scene--ending .care-scene__copy{width:min(1440px,100%);max-width:none;margin:auto;padding-inline:max(24px,calc((100vw - 1440px)/2));color:#fff}.care-scene--ending .care-scene__copy>*{max-width:560px}.care-scene--ending .care-scene__description,.care-scene--ending .care-scene__closing{color:#fffdfbd9}
@media(max-width:900px){.care-scene,.care-scene--hero,.care-scene--split,.care-scene--cinematic,.care-scene--reverse,.care-scene--detail,.care-scene--work,.care-scene--outdoor{width:100%;min-height:auto;grid-template-columns:1fr;gap:24px;padding:64px 18px}.care-scene__copy,.care-scene--hero .care-scene__copy,.care-scene--split .care-scene__copy,.care-scene--reverse .care-scene__copy,.care-scene--work .care-scene__copy{order:1}.care-scene__media,.care-scene--hero .care-scene__media,.care-scene--split .care-scene__media,.care-scene--cinematic .care-scene__media,.care-scene--reverse .care-scene__media,.care-scene--detail .care-scene__media,.care-scene--work .care-scene__media,.care-scene--outdoor .care-scene__media{order:2;height:auto;aspect-ratio:16/10;border-radius:20px}.care-scene--detail .care-scene__media{aspect-ratio:4/3}.care-scene--outdoor .care-scene__media{aspect-ratio:16/9}.care-scene--hero{padding-top:72px}.care-scene--hero .care-scene__media{aspect-ratio:4/3}.care-scene--hero .care-scene__number{position:static}.care-scene__title{margin:14px 0 10px;font-size:clamp(2.1rem,9vw,3.2rem)}.care-scene__hints{margin-top:24px}.care-scene__hints span{min-height:66px;font-size:.82rem}.care-scene--ending{height:auto;min-height:clamp(620px,84dvh,760px);display:flex;align-items:flex-end;padding:0}.care-scene--ending .care-scene__media{order:initial;aspect-ratio:auto;border-radius:0}.care-scene--ending .care-scene__media::after{background:linear-gradient(0deg,#493833e8 0%,#4938338f 42%,transparent 72%)}.care-scene--ending .care-scene__copy{order:1;padding:48px 18px}.care-scene__closing{margin-top:32px}}
@media(max-width:430px){.care-scene__hints{grid-template-columns:repeat(2,1fr)}}
@media(prefers-reduced-motion:reduce){.care-scene__image{will-change:auto}}
</style>
