<template>
  <q-page class="home-page"><main>
    <section ref="heroShell" class="hero" aria-labelledby="hero-title">
      <div class="hero__copy" data-hero-copy>
        <span class="kicker"><HeartHandshake :size="20" /> 照安心的照護理念</span>
        <h1 id="hero-title">照顧，有人陪伴<br><em>家人，才能放心一點</em></h1>
        <p>從尋找居服員、預約到服務完成，<br>每一步都替您整理好。</p>
        <div class="hero__actions"><router-link class="primary" to="/caregivers">尋找居服員 <ArrowRight :size="21" /></router-link><button class="secondary" @click="scrollToSection('journey')">了解服務</button></div>
      </div>
      <div class="hero-art" aria-hidden="true">
        <span class="sun"></span><svg viewBox="0 0 620 500"><path d="M27 376C116 337 165 369 235 327C302 287 306 208 389 176C455 151 532 177 594 124" /></svg>
        <div class="hand elder"><span class="sleeve"></span><span class="palm"></span><i v-for="n in 4" :key="`e${n}`" :class="`f f${n}`"></i></div>
        <div class="hand caregiver"><span class="sleeve"></span><span class="palm"></span><i v-for="n in 4" :key="`c${n}`" :class="`f f${n}`"></i></div>
        <small>伸出手，讓每一步都有依靠</small>
      </div>
    </section>

    <section class="philosophy section" aria-labelledby="philosophy-title" data-reveal><span class="kicker">照安心的照護理念</span><h2 id="philosophy-title">照護，不只是完成一件事情</h2><p>每一段照護關係，都從理解開始。聽見長輩真正的需要、尊重生活習慣與選擇，再找到適合的支持方式，才能讓服務融入日常，而不是增加彼此壓力。</p><p>照安心希望讓家屬、受照顧者與居服員，都能在更清楚的資訊與溝通中建立信任。</p><svg viewBox="0 0 500 70" aria-hidden="true"><path d="M5 42c88-33 136 16 218-5 65-17 125-50 272-15" /></svg></section>

    <section class="quick section" aria-labelledby="quick-title" data-reveal><header><div><span class="kicker">常用服務</span><h2 id="quick-title">今天需要什麼幫忙？</h2></div><p>選一個入口，就能開始。</p></header><div class="quick-grid" data-stagger><template v-for="(item,index) in quickActions" :key="item.title"><button v-if="item.scrollTo" class="quick-card" @click="scrollToSection(item.scrollTo)"><span class="num">0{{ index+1 }}</span><component :is="item.icon" :size="32"/><span><strong>{{ item.title }}</strong><small>{{ item.description }}</small></span><ChevronRight/></button><router-link v-else :to="item.to!" class="quick-card"><span class="num">0{{ index+1 }}</span><component :is="item.icon" :size="32"/><span><strong>{{ item.title }}</strong><small>{{ item.description }}</small></span><ChevronRight/></router-link></template></div></section>

    <section id="journey" class="journey section" aria-labelledby="journey-title"><header data-reveal><span class="kicker">從伸出手，到安心完成</span><h2 id="journey-title">照護安排，<br>一步一步接得住</h2><p>往下滑，看看照安心如何陪您走完每一段流程。</p></header><ol><li v-for="(step,index) in steps" :key="step.number" class="journey-card"><div><b>{{ step.number }}</b><h3>{{ step.title }}</h3><p>{{ step.description }}</p></div><div class="journey-art" aria-hidden="true"><span :class="{ sage:index%2 }"></span><component :is="step.icon" :size="78" :stroke-width="1.35"/></div></li></ol></section>

    <section class="care section" aria-labelledby="care-title" data-reveal><header><div><span class="kicker">真實安心夥伴</span><h2 id="care-title">找到適合相處，也適合照護的人</h2><p>透過服務資訊、經驗與個人介紹，找到更符合家庭需求的居服員。</p></div><router-link class="text-link" to="/caregivers">查看居服員 <ArrowRight :size="19"/></router-link></header>
      <div v-if="caregiverLoading" class="caregiver-row" aria-label="正在載入居服員"><q-skeleton v-for="n in 4" :key="n" type="rect" class="skeleton"/></div>
      <div v-else-if="caregiverError" class="state" role="status"><WifiOff/><div><strong>暫時讀不到居服員資料</strong><span>請稍後再試一次。</span></div><button @click="loadCaregivers">重新整理</button></div>
      <div v-else class="caregiver-row" aria-label="已認證且可接案的居服員" data-stagger><router-link v-for="c in caregivers.slice(0,6)" :key="c._id" to="/caregivers" class="caregiver-card"><div class="photo"><img :src="assetUrl(c.profilePhotoUrl)" :alt="`${caregiverName(c)}的居服員近照`" loading="lazy" @error="useFallbackPhoto"><span><BadgeCheck :size="17"/> 已認證</span></div><div class="body"><h3>{{ caregiverName(c) }}</h3><p><BriefcaseBusiness :size="17"/> {{ experienceLabel(c) }}</p><p><MapPin :size="17"/> {{ areaLabel(c) }}</p><b>看看詳細介紹 <ChevronRight :size="17"/></b></div></router-link></div>
    </section>

    <section id="subsidy" class="estimate section" aria-labelledby="estimate-title" data-reveal><div><span class="kicker">簡單試算</span><h2 id="estimate-title">長照費用，先一起算算看</h2><p>不用看複雜表格，只要完成四個選擇。</p><aside><ShieldCheck :size="22"/> 試算結果僅供專題展示，實際補助依主管機關核定。</aside></div><div class="calculator"><CareCostCalculator compact/></div></section>
    <section class="line-banner" aria-label="LINE 專人協助" data-reveal><MessageCircleHeart :size="42"/><div><span>不習慣操作網站也沒關係</span><h2>LINE 專人陪您一步一步完成</h2></div><button disabled>LINE 服務準備中</button></section>
  </main></q-page>
</template>

<script setup lang="ts">
import { markRaw,nextTick,onBeforeUnmount,onMounted,ref,watch } from 'vue';
import { ArrowRight,BadgeCheck,BriefcaseBusiness,Calculator,CalendarDays,CalendarHeart,CheckCheck,ChevronRight,HeartHandshake,House,MapPin,MessageCircleHeart,SearchCheck,ShieldCheck,Smartphone,UserRoundSearch,WifiOff } from '@lucide/vue';
import { api } from '@/boot/axios'; import CareCostCalculator from '@/components/CareCostCalculator.vue'; import { gsap } from '@/composables/useGsap';
interface Caregiver { _id:string; userId?:{name?:string}|string; profilePhotoUrl?:string; yearsExperience?:number; serviceAreas?:string[] }
const reduceMotion=window.matchMedia('(prefers-reduced-motion: reduce)').matches, heroSlide=ref('home'), caregivers=ref<Caregiver[]>([]), caregiverLoading=ref(true), caregiverError=ref(false), heroShell=ref<HTMLElement>(); let motionContext:gsap.Context|undefined;
const heroSlides=[{name:'home',to:'/caregivers'},{name:'meal',to:'/login'},{name:'connect',to:'/users'}];
const quickActions=[{title:'線上預約服務',description:'替自己或家人找幫手',icon:markRaw(CalendarHeart),to:'/login'},{title:'長照補助算算看',description:'四個選擇，簡單了解',icon:markRaw(Calculator),scrollTo:'subsidy'},{title:'查看居服員',description:'認識已通過審核的夥伴',icon:markRaw(UserRoundSearch),to:'/caregivers'}];
const steps=[{number:'01',icon:markRaw(SearchCheck),title:'找到合適的居服員',description:'查看服務資訊、經驗與個人介紹。'},{number:'02',icon:markRaw(CalendarDays),title:'建立照顧預約',description:'選擇受照顧者、服務內容、日期與時間。'},{number:'03',icon:markRaw(Smartphone),title:'居服員承接服務',description:'合適的居服員確認任務，服務安排正式成立。'},{number:'04',icon:markRaw(House),title:'出發並抵達',description:'掌握居服員出發、抵達與服務進度。'},{number:'05',icon:markRaw(CheckCheck),title:'服務完成',description:'完成服務並留下紀錄，家屬安心掌握。'}];
function caregiverName(c:Caregiver){return typeof c.userId==='object'?c.userId.name||'照安心夥伴':'照安心夥伴'}
function changeHero(direction:number){const i=heroSlides.findIndex(s=>s.name===heroSlide.value);heroSlide.value=heroSlides[(i+direction+heroSlides.length)%heroSlides.length]?.name||'home'}
function scrollToSection(id:string){document.getElementById(id)?.scrollIntoView({behavior:reduceMotion?'auto':'smooth',block:'start'})}
function experienceLabel(c:Caregiver){return c.yearsExperience?`${c.yearsExperience} 年服務經驗`:'新進照護夥伴'} function areaLabel(c:Caregiver){return c.serviceAreas?.slice(0,2).join('、')||'服務地區洽談'}
const apiBaseUrl=import.meta.env.VITE_API_BASE_URL||'http://localhost:3000/api',backendBaseUrl=apiBaseUrl.replace(/\/api\/?$/,'');
function assetUrl(path?:string){if(!path)return'/chioansimicon.svg';if(/^https?:\/\//.test(path))return path;const p=path.startsWith('/')?path:`/${path}`;return p.startsWith('/uploads/')?`${backendBaseUrl}${p}`:p}
function useFallbackPhoto(event:Event){const image=event.currentTarget as HTMLImageElement;image.src='/chioansimicon.svg';image.classList.add('is-fallback')}
async function loadCaregivers(){caregiverLoading.value=true;caregiverError.value=false;try{const{data}=await api.get<Caregiver[]>('/nurses');caregivers.value=data}catch{caregiverError.value=true}finally{caregiverLoading.value=false}}
function setupMotion(){if(reduceMotion||!heroShell.value)return;motionContext=gsap.context(()=>{gsap.timeline().from('[data-hero-copy] > *',{y:30,opacity:0,duration:.75,stagger:.09,ease:'power3.out'}).from('.caregiver',{x:-120,y:50,rotate:-4,opacity:0,duration:1.65,ease:'power3.out'},.25).from('.elder',{x:40,opacity:0,duration:1.55,ease:'power3.out'},.3).to('.hero-art',{y:-2,duration:3,repeat:-1,yoyo:true,ease:'sine.inOut'},1.8);gsap.utils.toArray<HTMLElement>('[data-reveal]').forEach(el=>gsap.from(el,{y:42,opacity:0,duration:.75,clearProps:'transform,opacity',scrollTrigger:{trigger:el,start:'top 84%',once:true}}));gsap.utils.toArray<HTMLElement>('[data-stagger]').forEach(el=>gsap.from(Array.from(el.children),{y:28,opacity:0,duration:.58,stagger:.1,clearProps:'transform,opacity',scrollTrigger:{trigger:el,start:'top 86%',once:true}}));gsap.matchMedia().add('(min-width: 901px)',()=>{const cards=gsap.utils.toArray<HTMLElement>('.journey-card');cards.forEach((card,i)=>{gsap.from(card,{y:130,rotate:i%2?2:-2,scale:.96,scrollTrigger:{trigger:card,start:'top 82%',end:'top 28%',scrub:.7}});const next=cards[i+1];if(next)gsap.to(card,{scale:.97,y:-14,opacity:.84,scrollTrigger:{trigger:next,start:'top 72%',end:'top 22%',scrub:true}})})});gsap.matchMedia().add('(max-width: 900px)',()=>gsap.utils.toArray<HTMLElement>('.journey-card').forEach(card=>gsap.from(card,{y:36,opacity:0,duration:.65,clearProps:'transform,opacity',scrollTrigger:{trigger:card,start:'top 88%',once:true}})))},heroShell.value.closest('main')||heroShell.value)}
watch(heroSlide,async()=>{await nextTick()});onMounted(async()=>{await loadCaregivers();await nextTick();setupMotion()});onBeforeUnmount(()=>motionContext?.revert());void changeHero;
</script>

<style scoped>
.home-page{--milk:#fff9f5;--paper:#fffdfb;--ink:#493833;--chestnut:#6e5750;--peach:#eb9079;--persimmon:#c85618;--sage:#4f7264;color:var(--ink);background:var(--milk)}main{padding:28px 24px 80px}.hero,.section,.line-banner{width:min(1180px,100%);margin-inline:auto}.hero{min-height:650px;display:grid;grid-template-columns:42fr 58fr;align-items:center;gap:30px;overflow:hidden;padding:clamp(36px,6vw,76px);background:var(--paper);border:1px solid #6e57501a;border-radius:32px;box-shadow:0 22px 60px #4e342b1a}.hero__copy{z-index:2}.kicker{display:inline-flex;align-items:center;gap:8px;color:var(--persimmon);font-weight:700;letter-spacing:.1em}.hero h1{margin:22px 0 20px;font-size:clamp(2.65rem,5vw,4.8rem);line-height:1.16}.hero h1 em{color:var(--persimmon);font-style:normal}.hero__copy p{color:var(--chestnut);font-size:1.2rem;line-height:1.8}.hero__actions{display:flex;gap:12px;margin-top:30px}.primary,.secondary{min-height:54px;display:inline-flex;align-items:center;justify-content:center;gap:8px;padding:0 23px;border-radius:15px;font:inherit;font-weight:700;text-decoration:none}.primary{color:#fff;background:var(--persimmon)}.secondary{color:var(--ink);background:transparent;border:1px solid #6e575059}.hero-art{position:relative;min-height:500px}.hero-art>svg{position:absolute;width:100%;height:100%;fill:none;stroke:#6e575047;stroke-width:2}.sun{position:absolute;width:360px;height:360px;right:5%;top:8%;background:#f9d9ca;border-radius:47% 53% 50% 46%}.hero-art small{position:absolute;right:5%;bottom:3%;color:var(--sage)}.hand{position:absolute;width:310px;height:125px;filter:drop-shadow(0 18px 18px #6e575024)}.palm{position:absolute;width:145px;height:88px;background:#efb28f;border:2px solid var(--ink);border-radius:46% 52% 44% 48%}.sleeve{position:absolute;width:150px;height:102px;border:2px solid var(--ink)}.f{position:absolute;width:106px;height:24px;background:#efb28f;border:2px solid var(--ink);border-radius:999px}.elder{right:-20px;top:115px;transform:rotate(8deg)}.elder .palm{right:95px;top:28px}.elder .sleeve{right:-50px;top:20px;background:var(--sage);border-radius:46% 0 0 46%}.elder .f{right:183px}.caregiver{left:-16px;bottom:95px;transform:rotate(-7deg)}.caregiver .palm{left:98px;top:24px;background:#e99a77}.caregiver .sleeve{left:-50px;top:17px;background:var(--peach);border-radius:0 46% 46% 0}.caregiver .f{left:187px;background:#e99a77}.f1{top:20px;transform:rotate(-7deg)}.f2{top:43px}.f3{top:66px;transform:rotate(6deg)}.f4{width:76px;top:88px;transform:rotate(23deg)}.caregiver .f1{transform:rotate(7deg)}.caregiver .f3{transform:rotate(-6deg)}.caregiver .f4{left:165px;transform:rotate(-23deg)}
.section{padding-top:115px}.section h2{margin:12px 0 22px;font-size:clamp(2rem,4vw,3.35rem);line-height:1.25}.philosophy{max-width:850px;text-align:center}.philosophy p{color:var(--chestnut);font-size:1.08rem;line-height:1.85}.philosophy svg{width:60%;fill:none;stroke:var(--peach);stroke-width:3}header{display:flex;align-items:flex-end;justify-content:space-between;gap:24px;margin-bottom:32px}header p{color:var(--chestnut)}.quick-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}.quick-card{position:relative;min-height:170px;display:grid;grid-template-columns:auto 1fr auto;align-items:end;gap:16px;padding:26px;color:var(--ink);background:var(--paper);border:1px solid #6e575026;border-radius:22px;box-shadow:0 14px 34px #4e342b12;text-align:left;text-decoration:none;transition:.18s;cursor:pointer}.quick-card:hover{transform:translateY(-4px)}.quick-card .num{position:absolute;top:18px;right:22px;color:#6e575040;font-size:1.5rem}.quick-card>span:not(.num){display:flex;flex-direction:column;gap:7px}.quick-card strong{font-size:1.2rem}.quick-card small{color:var(--chestnut)}
.journey{display:grid;grid-template-columns:34% 1fr;gap:7vw;padding-top:130px;scroll-margin-top:80px}.journey>header{position:sticky;top:130px;display:block;align-self:start}.journey ol{margin:0;padding:0 0 20vh;list-style:none}.journey-card{position:sticky;top:110px;min-height:430px;display:grid;grid-template-columns:1fr .82fr;align-items:center;gap:30px;margin-bottom:25vh;padding:55px;background:var(--paper);border:1px solid #6e575029;border-radius:28px;box-shadow:0 24px 52px #4e342b1f}.journey-card:last-child{margin-bottom:0}.journey-card b{color:var(--persimmon);letter-spacing:.16em}.journey-card h3{font-size:2.5rem;line-height:1.2}.journey-card p{color:var(--chestnut);font-size:1.06rem;line-height:1.75}.journey-art{position:relative;min-height:230px;display:grid;place-items:center}.journey-art span{position:absolute;width:190px;height:190px;background:#f9ded3;border-radius:46% 54%}.journey-art span.sage{background:#dce9e2}.journey-art svg{z-index:1}
.text-link{color:var(--persimmon);font-weight:700;text-decoration:none;white-space:nowrap}.caregiver-row{display:grid;grid-auto-flow:column;grid-auto-columns:minmax(250px,1fr);gap:20px;overflow-x:auto;padding:4px 4px 20px;scroll-snap-type:x mandatory}.caregiver-card{scroll-snap-align:start;overflow:hidden;color:var(--ink);background:var(--paper);border:1px solid #6e57501f;border-radius:22px;box-shadow:0 12px 30px #4e342b14;text-decoration:none}.photo{position:relative;height:230px;overflow:hidden;background:#f4e5de}.photo img{width:100%;height:100%;object-fit:cover}.photo img.is-fallback{padding:52px;object-fit:contain}.photo span{position:absolute;left:14px;bottom:14px;display:flex;gap:5px;padding:7px 11px;color:#315746;background:#eef8f1;border-radius:999px}.body{padding:20px}.body h3{font-size:1.4rem}.body p,.body b{display:flex;align-items:center;gap:7px;color:var(--chestnut)}.body b{color:var(--persimmon)}.skeleton{height:400px;border-radius:22px}.state{display:flex;justify-content:center;gap:16px;padding:28px;background:#fff1eb;border-radius:22px}.state div{display:flex;flex-direction:column}.state button{min-height:44px;color:#fff;background:var(--persimmon);border:0;border-radius:14px}.estimate{display:grid;grid-template-columns:.85fr 1.15fr;gap:6vw;align-items:center;margin-top:120px;padding:clamp(34px,6vw,72px);color:#fff;background:var(--chestnut);border-radius:30px;scroll-margin-top:92px}.estimate .kicker{color:#ffd4c8}.estimate>div>p{color:#f7e8e2}.estimate aside{display:flex;gap:10px;padding:16px;background:#ffffff1a;border-radius:16px}.calculator{padding:38px;color:var(--ink);background:var(--paper);border-radius:24px}.line-banner{display:flex;align-items:center;gap:22px;margin-top:88px;padding:28px 34px;color:#fff;background:var(--sage);border-radius:24px}.line-banner h2{margin:5px 0}.line-banner button{margin-left:auto;min-height:50px;padding:0 22px;color:#335649;background:#edf8f1;border:0;border-radius:14px}a:focus-visible,button:focus-visible{outline:3px solid #f3a089;outline-offset:3px}
@media(max-width:900px){main{padding-inline:16px}.hero{grid-template-columns:1fr;padding:50px 40px 25px}.hero-art{min-height:400px}.quick-grid{grid-template-columns:1fr}.quick-card{min-height:125px}.journey{display:block}.journey>header{position:static}.journey ol{padding:0}.journey-card{position:relative;top:auto;min-height:340px;margin-bottom:24px}.estimate{grid-template-columns:1fr}.line-banner{flex-wrap:wrap}.line-banner button{width:100%;margin:0}}
@media(max-width:599px){main{padding:12px 12px 48px}.hero{min-height:auto;padding:38px 22px 20px;border-radius:24px}.hero h1{font-size:2.55rem}.hero__copy p br{display:none}.hero__actions{display:grid;grid-template-columns:1fr 1fr}.primary,.secondary{padding:0 10px}.hero-art{min-height:320px;transform:scale(.9)}.sun{width:250px;height:250px}.elder{right:-90px;top:45px;transform:scale(.82) rotate(8deg)}.caregiver{left:-75px;bottom:45px;transform:scale(.82) rotate(-7deg)}.section{padding-top:76px}header{align-items:flex-start;flex-direction:column}.journey{padding-top:84px}.journey-card{display:block;min-height:390px;padding:30px 26px}.journey-card h3{font-size:2rem}.journey-art{min-height:180px}.estimate{margin-top:76px;padding:28px 16px}.calculator{padding:22px 14px}.state{flex-wrap:wrap}}
@media(prefers-reduced-motion:reduce){*,*::before,*::after{scroll-behavior:auto!important;transition:none!important;animation:none!important}}
</style>
